server {
    listen 80;
    root /usr/share/nginx/html;

    location /jeux-videops/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
