name: CI Jeux Videops

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci-two-ships:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install && npm install eslint@8.57.0 --save-dev

      - name: Audit Security (Two Ships)
        run: npm audit --audit-level=critical

      - name: Linting (Two Ships)
        env:
          ESLINT_USE_FLAT_CONFIG: false
        run: npx eslint games/two_ships/** -c games/two_ships/.eslintrc.js

      - name: Unit Tests (Two Ships)
        run: npm test tests/two-ships.test.mjs

  ci-space-word:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install && npm install eslint@8.57.0 --save-dev

      - name: Audit Security (Space Word)
        run: npm audit --audit-level=critical

      - name: Linting (Space Word)
        env:
          ESLINT_USE_FLAT_CONFIG: false
        run: npx eslint games/space_word/** -c games/space_word/.eslintrc.js

      - name: Unit Tests (Space Word)
        run: npm test tests/space-word.test.js
    