name: Frontend Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "dev", "main" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        run: npm install

      - name: Security Audit
        run: npm audit --audit-level=high

      - name: Lint Code (Syntax Check)
        run: npx eslint .

      - name: Build Launcher
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher-dist
          path: frontend/dist/

  deployment:
    needs: integration
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: launcher-dist
          path: ./frontend/dist

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/frontend:latest

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4